name: Deployment

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: 'Build: Initialize'
        run: /bin/bash -c "$(curl -fsSL https://dot.rayriffy.com)"
